services:
  - type: web
    name: telegram-anwer-web
    runtime: node
    plan: free
    region: frankfurt # or oregon, ohio, singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_ID
        value: "22043994"
      - key: API_HASH
        value: "56f64582b363d367280db96586b97801"
      - key: TDLIB_API_HASH
        value: "56f64582b363d367280db96586b97801"
      - key: SESSION_SECRET
        generateValue: true
      - key: VAPID_PUBLIC_KEY
        value: "BE36BmheMRx2GxzjWpp_4bmXq_hZg55bP_M_vNVysfnjTxns9VCI0hiCHgnRBx0URe_LoxWaAgrS9G9QZbQhOh8"
      - key: VAPID_PRIVATE_KEY
        value: "13NU1_GmeL7bDQcVtlFyuKqsnnsX3XkOyE--2rAQJw4"
      - key: VAPID_SUBJECT
        value: "mailto:anwrsaifanwr@gmail.com"
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
